# Generated by Django 3.0.7 on 2020-06-30 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 30, 17, 35, 26, 384234)),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 30, 17, 35, 26, 384210)),
        ),
    ]
