# Generated by Django 3.0.3 on 2020-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits_table',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_time',
            field=models.TimeField(),
        ),
    ]
