# Generated by Django 3.0.3 on 2020-06-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200602_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
