# Generated by Django 3.0.3 on 2020-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200602_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
