# Generated by Django 3.0.3 on 2020-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200602_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
