# Generated by Django 3.0.3 on 2020-06-02 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200602_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Submit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
