# Generated by Django 3.0.3 on 2020-06-03 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20200602_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
