# Generated by Django 3.0.3 on 2020-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200603_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Dispatched', 'Dispatched')], max_length=100),
        ),
    ]
