# Generated by Django 3.0.3 on 2020-06-05 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20200603_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
