# Generated by Django 3.0.3 on 2020-06-07 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20200605_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_finance_table',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('HOLD', 'HOLD'), ('DEAD', 'DEAD')], default='ACTIVE', max_length=100),
        ),
        migrations.AlterField(
            model_name='deposits_table',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Dispatched', 'Dispatched')], default='Recieved', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_interview',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('nomination_number', 'account_nominee_name')},
        ),
    ]
