# Generated by Django 3.0.7 on 2020-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20200607_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basic_details',
            unique_together={('last_name', 'father_name', 'id_number', 'first_name', 'village')},
        ),
    ]
