# Generated by Django 3.0.7 on 2020-06-08 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20200608_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits_table',
            name='account_opening_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
