# Generated by Django 3.0.7 on 2020-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20200608_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits_table',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE'), ('HOLD', 'HOLD'), ('DEAD', 'DEAD'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=100),
        ),
    ]
