# Generated by Django 3.0.7 on 2020-06-10 21:07

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20200609_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='photograph',
            field=cropperjs.models.CropperImageField(upload_to='users/images'),
        ),
    ]
