# Generated by Django 3.0.7 on 2020-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20200612_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocs',
            name='type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
