# Generated by Django 3.0.7 on 2020-06-27 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_documentprintcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterAndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('total_prints', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentprintcounter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='documentprintcounter',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='documentprintcounter',
            name='total_prints',
        ),
        migrations.AddField(
            model_name='documentprintcounter',
            name='counter_and_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.CounterAndTime'),
        ),
    ]
