# Generated by Django 3.0.7 on 2020-06-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20200627_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentprintcounter',
            name='counter_and_time',
        ),
        migrations.AddField(
            model_name='counterandtime',
            name='documentprintcounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.DocumentPrintCounter'),
        ),
    ]
