# Generated by Django 3.0.7 on 2020-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20200627_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterandtime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
