# Generated by Django 3.0.7 on 2020-06-29 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20200629_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
