# Generated by Django 3.0.7 on 2020-06-29 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20200629_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_interview',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
