# Generated by Django 3.0.7 on 2020-06-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200630_1735'),
        ('employee', '0025_auto_20200629_1944'),
    ]

    operations = [
    ]
