# Generated by Django 3.0.7 on 2020-07-01 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_merge_20200630_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='nominee_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_relation_choice', to='employee.Relation_Choice', to_field='relation_choice'),
        ),
    ]
