# Generated by Django 3.0.7 on 2020-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20200701_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_table',
            name='emi_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Quaterly', 'Quaterly')], max_length=100, null=True),
        ),
    ]
