# Generated by Django 3.0.7 on 2020-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20200701_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_finance',
            name='penalty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finance_table',
            name='emi_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('OneTime', 'OneTime')], max_length=100, null=True),
        ),
    ]
