# Generated by Django 3.0.7 on 2020-07-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_auto_20200707_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_finance_table',
            name='person',
        ),
    ]
