# Generated by Django 3.0.7 on 2020-07-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_remove_approved_finance_table_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_finance_table',
            name='emi_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('OneTime', 'OneTime')], default='Years', max_length=100, null=True),
        ),
    ]
