# Generated by Django 3.0.7 on 2020-08-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_cash_collection_total_cash_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentprintcounter',
            name='user',
        ),
        migrations.DeleteModel(
            name='CounterAndTime',
        ),
        migrations.DeleteModel(
            name='DocumentPrintCounter',
        ),
    ]
