# Generated by Django 3.0.7 on 2020-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_documentprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
