# Generated by Django 3.0.7 on 2020-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_voucher_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
