# Generated by Django 3.0.7 on 2020-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_voucher_custom_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
