# Generated by Django 3.0.7 on 2020-12-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_admin_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_interview',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
