# Generated by Django 3.0.7 on 2020-12-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_employee_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_table',
            name='gaurantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Gaurantor'),
        ),
    ]
