# Generated by Django 3.0.7 on 2021-01-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0043_auto_20210106_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawl_entry',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee_interview'),
        ),
    ]
