# Generated by Django 3.0.7 on 2021-01-07 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_withdrawl_entry_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_collection',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cheque_details',
            name='cheque_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection_deposit',
            name='payment_received_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='collection_finance',
            name='loan_emi_received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposits_table',
            name='account_opening_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documents',
            name='Submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploaddocs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawl_entry',
            name='amount_withdrawl_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
