"""
Django settings for sidhi_society project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import os
import pwd
# from easy_thumbnails import defaults
def get_username():
    return pwd.getpwuid( os.getuid() )[ 0 ]
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

print(get_username())
if(get_username()=='vaqasahmed'):
    pass_ = 'Vaqasahmed!2'
    db = 'lite'
else:
    pass_ = 'kdsfmsbAAMNVJHFHVjvhjhfks8736587365smdnbmfnsdbf2836487sdjbfjsd'
    db = 'postgre'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u^s)wt5+^4kxqm5ac=8qvyuacx7whuec-j0@m-t55i)v$3k0k)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'accounts',
    'employee',
    'crispy_forms',
    'django_crontab',
    'dbbackup',
    'cropperjs',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'accounts.middleware.OneSessionPerUserMiddleware'
]

CRONJOBS = [
    ('30 1 * * *', 'employee.emp_admin.cron.daily'),
    ('30 1 1 * *', 'employee.emp_admin.cron.monthly'),
    ('30 1 * * *', 'employee.emp_admin.cron.ten_day_no_deposit')
]


ROOT_URLCONF = 'sidhi_society.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sidhi_society.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DB_bitches = {
    'lite': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'banking_data',
        'USER': 'vaqas',
        'PASSWORD': pass_,
        'HOST': '35.223.125.21',
        'PORT': '5432',
    },
       'postgre': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'banking_data',
        'USER': 'vaqas',
        'PASSWORD': pass_,
        'HOST': 'localhost',
        'PORT': '',
    },

    'db':{

        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

}

#For debugging

DATABASES = {'default':  {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
}}

# DATABASES = {
#     'default':  {   
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'banking_data',
#         'USER': 'vaqas',
#         'PASSWORD': pass_,
#         'HOST': 'localhost',
#         'PORT': '',
#     },
#     'dummy':{   
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dummy',
#         'USER': 'vaqas',
#         'PASSWORD': pass_,
#         'HOST': 'localhost',
#         'PORT': '',
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'login'


SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 900  # 1 hour

#### Backup shit
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/Users/vaqasahmed/Documents/sidhi_docs'}

